### PR TITLE
Updating docs, tweaks to uploader

### PR DESCRIPTION
**Pull request by dylanmc**

### CODE REVIEW

**Comment by dylanmc** [comment]
Jesse, the new version of tweetyUploader.py is the one we want to keep (the one I'm making the pull request for).  Do you have the git expertise to process the pull request?

**Comment by HedronUser** [comment]
yea, very easy. I will merge.



      Jesse Jenkins

      Hedron <http://hedron.technology/>
      <http://hedron.technology>

**Comment by HedronUser** [comment]
Please verify code still works.

**Comment by dylanmc** [comment]
Looks good!

**Pull request merged**
